### ISSUE TITLE
storybook@3.3 overrides URLs

### ISSUE THREAD

**Issue by arahansen** [obartra/picturebook#22]
Picturebook relies on adding a url flag `isCi` to remove text from elements. The latest version of storybook seems to be overriding the url value.

On storybook@3.3.3, picturebook takes screenshots with text visible. By downgrading to storybook@3.2.16, the problem resolves itself.

I think we may want to explore solutions that don't depend on the global state of the url (where anything could override it). Perhaps an environment variable that gets picked up by webpack, that specifies when we are running in CI for image comparisons?

**Comment by obartra** [comment]
V2 doesn't replace text, closing for now since picturebook no longer relies on this flag
