### ISSUE TITLE
Better surfacing of errors

### ISSUE THREAD

**Issue by colinlgray** [obartra/picturebook#28]
This might be something that needs to be filed in nightwatch instead of picturebook but for anyone having issues related to lack of errors this might be helpful.

Issue:
If an error occurs within picturebook, the command `./node_modules/.bin/picturebook-image` will exit with code 1 and not give an error message when the process fails.

Steps to reproduce:
Inside a picurebook file like /test/screenshot/specs/index.js manually throw an error. I placed `throw new Error("Test error")` at the top of the file. (A real scenario for this was that I happened to be running an old version of node where `Object.values` did not exist and threw an error) Then running `./node_modules/.bin/picturebook-image` will fail without give an error.

Expected output:
```
$ ./node_modules/.bin/picturebook-image


Starting selenium server in parallel mode... started - PID:  5384

Started child process for: index

  >> index finished.

There was an error while starting the test runner:
Error: Test error
    at Object.<anonymous> (/Users/cgray/repos/iris/electra/node_modules/picturebook/test/screenshot/specs/index.js:11:7)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/cgray/repos/iris/electra/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at new Module (/Users/cgray/repos/iris/electra/node_modules/nightwatch/lib/runner/module.js:7:23)
```

Actual Output:
```
$ ./node_modules/.bin/picturebook-image


Starting selenium server in parallel mode... started - PID:  5384

Started child process for: index

  >> index finished.
```

Additional information:
From what I could tell this is not something that is easily surfaced from nightwatch. Nightwatch captures the output of the child process, in this case picturebook, and will invoke the callback with the output as a parameter [here](https://github.com/nightwatchjs/nightwatch/blob/master/lib/runner/cli/child-process.js#L87). That callback that it calls with the output is defined [here](https://github.com/nightwatchjs/nightwatch/blob/master/lib/runner/cli/clirunner.js#L824). It appears that it is just swallowing that error output. However even if it were calling some function with that output it wouldn't get back to us because we don't init the runner with any callback, we just give it the cli parameters. Those functions are defined [here](https://github.com/nightwatchjs/nightwatch/blob/master/bin/runner.js#L10) and [here](https://github.com/nightwatchjs/nightwatch/blob/master/lib/index.js#L549).

I tried looking at the config file that we do pass to see if there was an option to pass some sort of callback or log through the config but didn't have any luck. I thought it would be best to bring this up to the community before attempting a solution. And also to give direction to anyone using this library that is having this problem. For now if the nightwatch library is manually modified to log out `self.env_output` the messages will be described there.

Edit: Original information I posted was slightly incorrect. Updated with more detail

**Comment by obartra** [comment]
V2 (now in beta should solve this issue)
