### ISSUE TITLE
Add React Native Support

### ISSUE THREAD

**Issue by arahansen** [obartra/picturebook#7]
Add an option to run picturebook in React Native. This is an example of a minimal setup for react native storybook:

```js
// storybook/stories/index.js
import React from 'react';
import { View } from 'react-native';

import { storiesOf } from '@storybook/react-native';

import Button from './Button';
import CenterView from './CenterView';
import Welcome from './Welcome';

storiesOf('Welcome', module).add('to Storybook', () => <View />);

// storybook/index.js
import { getStorybookUI, configure } from '@storybook/react-native';

// import stories
configure(() => {
  require('./stories');
}, module);

const StorybookUI = getStorybookUI({ port: 7007, host: 'localhost' });
export default StorybookUI;
```

[See here](https://github.com/storybooks/storybook/tree/master/app/react-native) for more details on setting up React Native projects in storybook.

**Comment by arahansen** [comment]
Will also need to decouple [index.js](https://github.com/obartra/picturebook/blob/master/index.js) such that `storiesOf` can be pulled from `@storybook/react-native` instead of `@storybook/react`

**Comment by obartra** [comment]
Can you check if RN is supported? I imagine it should be although that's a good case to remove `@storybook/react` as a peer dependency as well since the consumer can choose what they (react / RN)

**Comment by arahansen** [comment]
Looks like there's a [dedicated react-native package](https://github.com/storybooks/storybook/blob/master/app/react-native/package.json)

**Comment by obartra** [comment]
Yeah that's what I meant, that I agree with your comment before on storybook not being a peer dependency since one may want to use RN instead of the react one
